AWSTemplateFormatVersion: 2010-09-09
Description: >-
  qd-app-login

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String

  # For our own UserPool
  EmailVerificationMessage:
    Type: String
    Default: "Your verification code is {####}"

  EmailVerificationSubject:
    Type: String
    Default: "Your verification code"

Resources:

  UserPool:
    Type: AWS::Cognito::UserPool
    # DeletionPolicy: Retain
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-UserPool"
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      UsernameConfiguration:
        CaseSensitive: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true

        - Name: family_name
          AttributeDataType: String
          Required: true
          Mutable: true

        - Name: given_name
          AttributeDataType: String
          Required: true
          Mutable: true

        - Name: nickname
          Required: true
          Mutable: true

      AutoVerifiedAttributes:
        - email

      EmailVerificationMessage: !Ref EmailVerificationMessage
      EmailVerificationSubject: !Ref EmailVerificationSubject
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  UserPoolUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: "Users"
      UserPoolId: !Ref UserPool

  UserPoolAdministratorGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: "Administrators"
      UserPoolId: !Ref UserPool

  UserPoolWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-webclient"
      CallbackURLs:
        - Fn::Join: ["", ["https://", Fn::ImportValue: !Sub "qd-infra-base-${Environment}:HostedZone:DomainName", "/" ]]
      LogoutURLs:
        - Fn::Join: ["", ["https://", Fn::ImportValue: !Sub "qd-infra-base-${Environment}:HostedZone:DomainName", "/logout" ]]
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      RefreshTokenValidity: 7
      AccessTokenValidity:  60
      IdTokenValidity:  60
      UserPoolId: !Ref UserPool
      ReadAttributes:
        - email
        - email_verified
        - family_name
        - given_name
        - nickname
        - updated_at
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO


Outputs :
  UserPoolId:
    Value: !Ref UserPool
    Description: UserPoolId
    Export:
      Name: !Sub "${AWS::StackName}:UserPoolId"

  UserPoolArn:
    Value: !GetAtt UserPool.Arn
    Description: UserPool Arn
    Export:
      Name: !Sub "${AWS::StackName}:UserPoolArn"

  UserPoolWebClientId:
    Value: !Ref UserPoolWebClient
    Description: ClientId
    Export:
      Name: !Sub "${AWS::StackName}:UserPoolClientWebPortalClientId"
